### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by avinash-kokare-dev** [chicolucio/truth-table-generator#5]
I am getting KeyError for the particular case
case - (p=>q)=(~p=>~q)
this case causes an error. Please help me to solve the error
Error found at file ttg.py at line number 103

**Comment by chicolucio** [comment]
Hi! Sorry to take so long to reply.

As noted in the readme, use parentheses with the negation operator. Although precedence rules are used, sometimes the negation operator raises errors (still working on it), so provide it explicitly in a given formula with parentheses.

In your example: `(p=>q)=((~p)=>(~q))`

A full table with your example, now with parentheses, with the CLI:

input: 

`$ ttg_cli.py "['p', 'q']" -p "['~p', '~q', 'p=>q','(~p)=>(~q)','(p=>q)=((~p)=>(~q))']"`

output:

```
+-----+-----+------+------+--------+--------------+-----------------------+
|  p  |  q  |  ~p  |  ~q  |  p=>q  |  (~p)=>(~q)  |  (p=>q)=((~p)=>(~q))  |
|-----+-----+------+------+--------+--------------+-----------------------|
|  1  |  1  |  0   |  0   |   1    |      1       |           1           |
|  1  |  0  |  0   |  1   |   0    |      1       |           0           |
|  0  |  1  |  1   |  0   |   1    |      0       |           0           |
|  0  |  0  |  1   |  1   |   1    |      1       |           1           |
+-----+-----+------+------+--------+--------------+-----------------------+
```
